### ISSUE TITLE
Add Discord Rich Presence Into This

### ISSUE THREAD

**Issue by PenPow** [thaumatrge/wordsmith#1]
**Describe the ideal solution**
Implement the discord.js RPC api (https://github.com/discordjs/RPC/tree/master/example) to dynamically update depending on what you are doing inside the app

**Additional context**
N/A

**Comment by thaumatrge** [comment]
Interesting idea. Whilst this isn't necessary right now, this will certainly be implemented for the next release.

**Comment by thaumatrge** [comment]
Start a pull request for this.

**Comment by thaumatrge** [comment]
Please start the pull request.
